-- MySQL Script generated by MySQL Workbench
-- Sat Oct 11 23:26:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecoraee-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecoraee-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecoraee-db` DEFAULT CHARACTER SET latin1 ;
USE `ecoraee-db` ;

-- -----------------------------------------------------
-- Table `ecoraee-db`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`roles` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`roles` (
  `idRoles` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombres_Roles` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`provincias` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`provincias` (
  `idProvincias` INT ZEROFILL NOT NULL,
  `Nombres_Provincias` VARCHAR(50) NULL,
  PRIMARY KEY (`idProvincias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`municipios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`municipios` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`municipios` (
  `idMunicipios` INT NOT NULL AUTO_INCREMENT,
  `Nombres_Municipios` VARCHAR(100) NULL,
  `CodigoPostal_Municipios` VARCHAR(10) NULL,
  `idProvincias_Municipios` INT NOT NULL,
  PRIMARY KEY (`idMunicipios`),
  INDEX `fk_municipios_provincias1_idx` (`idProvincias_Municipios` ASC) VISIBLE,
  CONSTRAINT `fk_municipios_provincias1`
    FOREIGN KEY (`idProvincias_Municipios`)
    REFERENCES `ecoraee-db`.`provincias` (`idProvincias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`direcciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`direcciones` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`direcciones` (
  `idDirecciones` INT(11) NOT NULL AUTO_INCREMENT,
  `Calle_Direcciones` VARCHAR(100) NULL DEFAULT NULL,
  `Numero_Direcciones` VARCHAR(10) NULL DEFAULT NULL,
  `Piso_Direcciones` VARCHAR(10) NULL,
  `Departamento_Direcciones` VARCHAR(10) NULL,
  `Barrio_Direcciones` VARCHAR(100) NULL,
  `Longitud_Ubicaciones` DECIMAL(10,8) NULL DEFAULT NULL,
  `Latitud_Ubicaciones` DECIMAL(10,8) NULL DEFAULT NULL,
  `idMunicipios_Direcciones` INT NOT NULL,
  PRIMARY KEY (`idDirecciones`),
  INDEX `idx_ubicaciones_coordenadas` (`Latitud_Ubicaciones` ASC, `Longitud_Ubicaciones` ASC) VISIBLE,
  INDEX `fk_direcciones_municipios1_idx` (`idMunicipios_Direcciones` ASC) VISIBLE,
  CONSTRAINT `fk_direcciones_municipios1`
    FOREIGN KEY (`idMunicipios_Direcciones`)
    REFERENCES `ecoraee-db`.`municipios` (`idMunicipios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`usuarios` (
  `idUsuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `DNI_Usuarios` VARCHAR(10) NOT NULL,
  `Nombres_Usuarios` VARCHAR(50) NOT NULL,
  `Apellidos_Usuarios` VARCHAR(50) NOT NULL,
  `Password_Usuarios` VARCHAR(255) NOT NULL,
  `Telefono_Usuarios` VARCHAR(14) NOT NULL,
  `Email_Usuarios` VARCHAR(100) NOT NULL,
  `Puntos_Usuarios` INT(11) NOT NULL,
  `Roles_Usuarios` INT(11) NOT NULL,
  `idDirecciones_Usuarios` INT(11) NOT NULL,
  `ImagenPerfil_Usuarios` VARCHAR(255) NULL DEFAULT NULL,
  `FechaRegistro_Usuarios` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `Activo_Usuarios` TINYINT(4) NULL DEFAULT 1,
  PRIMARY KEY (`idUsuarios`),
  INDEX `idx_clientes_documento` (`DNI_Usuarios` ASC) VISIBLE,
  INDEX `idx_clientes_telefono` (`Telefono_Usuarios` ASC) VISIBLE,
  INDEX `idx_clientes_email` (`Email_Usuarios` ASC) VISIBLE,
  INDEX `fk_clientes_roles1_idx` (`Roles_Usuarios` ASC) VISIBLE,
  INDEX `idx_usuarios_activo` (`Activo_Usuarios` ASC) VISIBLE,
  INDEX `fk_usuarios_direcciones1_idx` (`idDirecciones_Usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_roles1`
    FOREIGN KEY (`Roles_Usuarios`)
    REFERENCES `ecoraee-db`.`roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_direcciones1`
    FOREIGN KEY (`idDirecciones_Usuarios`)
    REFERENCES `ecoraee-db`.`direcciones` (`idDirecciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`carrito_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`carrito_compras` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`carrito_compras` (
  `idCarrito_Compras` INT(11) NOT NULL AUTO_INCREMENT,
  `PuntosCanjeados_Carrito` INT(11) NULL,
  `FechaEgreso_Carrito` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `usuarios_idUsuarios` INT(11) NOT NULL,
  PRIMARY KEY (`idCarrito_Compras`),
  INDEX `idx_carrito_fecha` (`FechaEgreso_Carrito` ASC) VISIBLE,
  INDEX `fk_carrito_compras_usuarios1_idx` (`usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_compras_usuarios1`
    FOREIGN KEY (`usuarios_idUsuarios`)
    REFERENCES `ecoraee-db`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`categorias_equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`categorias_equipos` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`categorias_equipos` (
  `idCategorias` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombres_Categorias` VARCHAR(50) NOT NULL,
  `PuntosBase_Categorias` DECIMAL(3,2) NOT NULL DEFAULT 50,
  PRIMARY KEY (`idCategorias`),
  UNIQUE INDEX `Nombres_Categorias` (`Nombres_Categorias` ASC) VISIBLE,
  INDEX `idx_categorias_puntos` (`PuntosBase_Categorias` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`estados_equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`estados_equipos` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`estados_equipos` (
  `idEstadosEquipos` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombres_EstadosEquipos` VARCHAR(50) NOT NULL,
  `MultiplicadorPuntos_EstadosEquipos` DECIMAL(3,2) NOT NULL DEFAULT 1.00,
  PRIMARY KEY (`idEstadosEquipos`),
  INDEX `idx_estados_multiplicador` (`MultiplicadorPuntos_EstadosEquipos` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`marcas_equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`marcas_equipos` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`marcas_equipos` (
  `idMarcas` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombres_Marcas` VARCHAR(50) NOT NULL,
  `PuntosBase_Marcas` DECIMAL(3,2) NOT NULL DEFAULT 50,
  PRIMARY KEY (`idMarcas`),
  UNIQUE INDEX `Nombres_Categorias` (`Nombres_Marcas` ASC) VISIBLE,
  INDEX `idx_categorias_puntos` (`PuntosBase_Marcas` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`equipos` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`equipos` (
  `idEquipos` INT(11) NOT NULL AUTO_INCREMENT,
  `idCategorias_Equipos` INT(11) NOT NULL,
  `idMarcas_Equipos` INT(11) NOT NULL,
  `Modelo_Equipos` VARCHAR(50) NULL,
  `Descripcion_Equipos` VARCHAR(255) NULL DEFAULT NULL,
  `idEstados_Equipos` INT(11) NOT NULL,
  `PesoKG_Equipos` DOUBLE NOT NULL,
  `DimencionesCM_Equipos` VARCHAR(20) NULL DEFAULT NULL,
  `Accesorios_Equipos` VARCHAR(100) NULL DEFAULT NULL,
  `FechaIngreso_Equipos` DATETIME NULL DEFAULT NULL,
  `ImagenPrincipal_Equipos` VARCHAR(255) NULL DEFAULT NULL,
  `idUsuarios_Equipos` INT(11) NOT NULL,
  PRIMARY KEY (`idEquipos`),
  INDEX `idx_equipos_fecha_ingreso` (`FechaIngreso_Equipos` ASC) VISIBLE,
  INDEX `idx_equipos_categoria` (`idCategorias_Equipos` ASC) VISIBLE,
  INDEX `fk_equipos_estados1_idx` (`idEstados_Equipos` ASC) VISIBLE,
  INDEX `idx_equipos_imagen` (`ImagenPrincipal_Equipos` ASC) VISIBLE,
  INDEX `fk_equipos_marcas_equipos1_idx` (`idMarcas_Equipos` ASC) VISIBLE,
  INDEX `fk_equipos_usuarios1_idx` (`idUsuarios_Equipos` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_categorias1`
    FOREIGN KEY (`idCategorias_Equipos`)
    REFERENCES `ecoraee-db`.`categorias_equipos` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipos_estados1`
    FOREIGN KEY (`idEstados_Equipos`)
    REFERENCES `ecoraee-db`.`estados_equipos` (`idEstadosEquipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipos_marcas_equipos1`
    FOREIGN KEY (`idMarcas_Equipos`)
    REFERENCES `ecoraee-db`.`marcas_equipos` (`idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipos_usuarios1`
    FOREIGN KEY (`idUsuarios_Equipos`)
    REFERENCES `ecoraee-db`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`historial_puntos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`historial_puntos` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`historial_puntos` (
  `idHistorialPuntos` INT(11) NOT NULL AUTO_INCREMENT,
  `PuntosInicial_Puntos` INT(11) NULL DEFAULT NULL,
  `PuntosCambiados_Puntos` INT(11) NULL DEFAULT NULL,
  `PuntosTotales_Puntos` INT(11) NULL DEFAULT NULL,
  `idEquipos_Puntos` INT(11) NOT NULL,
  `FechaMovimiento_Puntos` DATETIME NOT NULL,
  PRIMARY KEY (`idHistorialPuntos`),
  INDEX `fk_Puntos_equipos1_idx` (`idEquipos_Puntos` ASC) VISIBLE,
  INDEX `idx_historial_fecha` (`FechaMovimiento_Puntos` ASC) VISIBLE,
  CONSTRAINT `fk_Puntos_equipos1`
    FOREIGN KEY (`idEquipos_Puntos`)
    REFERENCES `ecoraee-db`.`equipos` (`idEquipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`publicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`publicacion` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`publicacion` (
  `idPublicacion` INT(11) NOT NULL AUTO_INCREMENT,
  `Titulo_Publicacion` VARCHAR(100) NULL DEFAULT NULL,
  `Descripcion_Publicacion` VARCHAR(255) NOT NULL,
  `PuntosDonados_Publicacion` INT(11) NOT NULL,
  `FechaIngreso_Publicacion` DATETIME NOT NULL,
  PRIMARY KEY (`idPublicacion`),
  INDEX `idx_publicacion_titulo` (`Titulo_Publicacion` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`punto_entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`punto_entrega` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`punto_entrega` (
  `idPuntoEntrega` INT(11) NOT NULL AUTO_INCREMENT,
  `FechaMovimiento_PuntoEntrega` DATETIME NULL DEFAULT NULL,
  `direcciones_idDirecciones` INT(11) NOT NULL,
  PRIMARY KEY (`idPuntoEntrega`),
  INDEX `idx_ubicaciones_recoleccion_fecha` (`FechaMovimiento_PuntoEntrega` ASC) VISIBLE,
  INDEX `fk_punto_entrega_direcciones1_idx` (`direcciones_idDirecciones` ASC) VISIBLE,
  CONSTRAINT `fk_punto_entrega_direcciones1`
    FOREIGN KEY (`direcciones_idDirecciones`)
    REFERENCES `ecoraee-db`.`direcciones` (`idDirecciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`tipo_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`tipo_detalles` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`tipo_detalles` (
  `idTipoDetalles` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Detalles` TINYINT NULL,
  PRIMARY KEY (`idTipoDetalles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`detalles` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`detalles` (
  `idPublicacion_DetallePublicacion` INT(11) NOT NULL,
  `idEquipos_DetallePublicacion` INT(11) NOT NULL,
  `carrito_compras_idCarrito_Compras` INT(11) NOT NULL,
  `Cantidad_Detalle` INT(11) NULL,
  `idTipoDetalles_Detalle` INT NOT NULL,
  INDEX `fk_detalle_publicacion_publicacion1_idx` (`idPublicacion_DetallePublicacion` ASC) VISIBLE,
  INDEX `fk_detalle_publicacion_equipos1_idx` (`idEquipos_DetallePublicacion` ASC) VISIBLE,
  PRIMARY KEY (`idPublicacion_DetallePublicacion`, `idEquipos_DetallePublicacion`, `carrito_compras_idCarrito_Compras`),
  INDEX `fk_detalle_publicacion_carrito_compras1_idx` (`carrito_compras_idCarrito_Compras` ASC) VISIBLE,
  INDEX `fk_detalles_tipo_detalles1_idx` (`idTipoDetalles_Detalle` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_publicacion_publicacion1`
    FOREIGN KEY (`idPublicacion_DetallePublicacion`)
    REFERENCES `ecoraee-db`.`publicacion` (`idPublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_publicacion_equipos1`
    FOREIGN KEY (`idEquipos_DetallePublicacion`)
    REFERENCES `ecoraee-db`.`equipos` (`idEquipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_publicacion_carrito_compras1`
    FOREIGN KEY (`carrito_compras_idCarrito_Compras`)
    REFERENCES `ecoraee-db`.`carrito_compras` (`idCarrito_Compras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalles_tipo_detalles1`
    FOREIGN KEY (`idTipoDetalles_Detalle`)
    REFERENCES `ecoraee-db`.`tipo_detalles` (`idTipoDetalles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoraee-db`.`fotos_equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoraee-db`.`fotos_equipos` ;

CREATE TABLE IF NOT EXISTS `ecoraee-db`.`fotos_equipos` (
  `idFotosEquipos` INT NOT NULL AUTO_INCREMENT,
  `URL_FotosEquipos` TEXT NULL,
  `idEquipos_FotosEquipos` INT(11) NOT NULL,
  PRIMARY KEY (`idFotosEquipos`),
  INDEX `fk_fotos_equipos_equipos1_idx` (`idEquipos_FotosEquipos` ASC) VISIBLE,
  CONSTRAINT `fk_fotos_equipos_equipos1`
    FOREIGN KEY (`idEquipos_FotosEquipos`)
    REFERENCES `ecoraee-db`.`equipos` (`idEquipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
